import { carburantFeature } from './carburant.reducer';

export const {
  selectStockOverview,
  selectStockLoading,
  selectStockError,
  selectDevis,
  selectDevisLoading,
  selectDevisError,
  selectDevisSaving,
  selectCommandes,
  selectCommandesLoading,
  selectCommandesError,
  selectLivraisons,
  selectLivraisonsLoading,
  selectLivraisonsError,
  selectFactures,
  selectFacturesLoading,
  selectFacturesError,
  selectAvoirs,
  selectAvoirsLoading,
  selectAvoirsError,
  selectDevisAchat,
  selectDevisAchatLoading,
  selectDevisAchatError,
  selectDevisAchatSaving,
  selectCommandesAchat,
  selectCommandesAchatLoading,
  selectCommandesAchatError,
  selectCommandesAchatSaving,
  selectReceptions,
  selectReceptionsLoading,
  selectReceptionsError,
  selectReceptionsSaving,
  selectFacturesFournisseur,
  selectFacturesFournisseurLoading,
  selectFacturesFournisseurError,
  selectFacturesFournisseurSaving,
  selectAvoirsFournisseur,
  selectAvoirsFournisseurLoading,
  selectAvoirsFournisseurError,
  selectAvoirsFournisseurSaving,
} = carburantFeature;
