import { inject, Injectable } from '@angular/core';
import { Actions, createEffect, ofType } from '@ngrx/effects';
import { catchError, map, of, switchMap } from 'rxjs';
import { AchatApi } from '../data-access/achat.api';
import { AchatActions } from './achat.actions';

@Injectable()
export class AchatEffects {
  private readonly actions$ = inject(Actions);
  private readonly api = inject(AchatApi);

  loadDevisAchat$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.loadDevisAchat), switchMap(() => this.api.getDevisAchat().pipe(map((d) => AchatActions.loadDevisAchatSuccess({ devisAchat: d })), catchError((e) => of(AchatActions.loadDevisAchatFailure({ error: e?.message ?? 'Erreur' })))))));
  addDevisAchat$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.addDevisAchat), switchMap(({ draft }) => this.api.addDevisAchat(draft).pipe(map((d) => AchatActions.addDevisAchatSuccess({ devisAchat: d })), catchError((e) => of(AchatActions.addDevisAchatFailure({ error: e?.message ?? 'Erreur' })))))));
  updateDevisAchat$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.updateDevisAchat), switchMap(({ id, draft }) => this.api.updateDevisAchat(id, draft).pipe(map((d) => AchatActions.updateDevisAchatSuccess({ devisAchat: d })), catchError((e) => of(AchatActions.updateDevisAchatFailure({ error: e?.message ?? 'Erreur' })))))));
  removeDevisAchat$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.removeDevisAchat), switchMap(({ id }) => this.api.removeDevisAchat(id).pipe(map(() => AchatActions.removeDevisAchatSuccess({ id })), catchError((e) => of(AchatActions.removeDevisAchatFailure({ error: e?.message ?? 'Erreur' })))))));

  loadCommandesAchat$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.loadCommandesAchat), switchMap(() => this.api.getCommandesAchat().pipe(map((d) => AchatActions.loadCommandesAchatSuccess({ commandesAchat: d })), catchError((e) => of(AchatActions.loadCommandesAchatFailure({ error: e?.message ?? 'Erreur' })))))));
  addCommandeAchat$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.addCommandeAchat), switchMap(({ draft }) => this.api.addCommandeAchat(draft).pipe(map((d) => AchatActions.addCommandeAchatSuccess({ commandeAchat: d })), catchError((e) => of(AchatActions.addCommandeAchatFailure({ error: e?.message ?? 'Erreur' })))))));
  updateCommandeAchat$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.updateCommandeAchat), switchMap(({ id, draft }) => this.api.updateCommandeAchat(id, draft).pipe(map((d) => AchatActions.updateCommandeAchatSuccess({ commandeAchat: d })), catchError((e) => of(AchatActions.updateCommandeAchatFailure({ error: e?.message ?? 'Erreur' })))))));
  removeCommandeAchat$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.removeCommandeAchat), switchMap(({ id }) => this.api.removeCommandeAchat(id).pipe(map(() => AchatActions.removeCommandeAchatSuccess({ id })), catchError((e) => of(AchatActions.removeCommandeAchatFailure({ error: e?.message ?? 'Erreur' })))))));

  loadReceptions$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.loadReceptions), switchMap(() => this.api.getReceptions().pipe(map((d) => AchatActions.loadReceptionsSuccess({ receptions: d })), catchError((e) => of(AchatActions.loadReceptionsFailure({ error: e?.message ?? 'Erreur' })))))));
  addReception$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.addReception), switchMap(({ draft }) => this.api.addReception(draft).pipe(map((d) => AchatActions.addReceptionSuccess({ reception: d })), catchError((e) => of(AchatActions.addReceptionFailure({ error: e?.message ?? 'Erreur' })))))));
  updateReception$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.updateReception), switchMap(({ id, draft }) => this.api.updateReception(id, draft).pipe(map((d) => AchatActions.updateReceptionSuccess({ reception: d })), catchError((e) => of(AchatActions.updateReceptionFailure({ error: e?.message ?? 'Erreur' })))))));
  removeReception$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.removeReception), switchMap(({ id }) => this.api.removeReception(id).pipe(map(() => AchatActions.removeReceptionSuccess({ id })), catchError((e) => of(AchatActions.removeReceptionFailure({ error: e?.message ?? 'Erreur' })))))));

  loadFacturesFournisseur$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.loadFacturesFournisseur), switchMap(() => this.api.getFacturesFournisseur().pipe(map((d) => AchatActions.loadFacturesFournisseurSuccess({ facturesFournisseur: d })), catchError((e) => of(AchatActions.loadFacturesFournisseurFailure({ error: e?.message ?? 'Erreur' })))))));
  addFactureFournisseur$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.addFactureFournisseur), switchMap(({ draft }) => this.api.addFactureFournisseur(draft).pipe(map((d) => AchatActions.addFactureFournisseurSuccess({ factureFournisseur: d })), catchError((e) => of(AchatActions.addFactureFournisseurFailure({ error: e?.message ?? 'Erreur' })))))));
  updateFactureFournisseur$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.updateFactureFournisseur), switchMap(({ id, draft }) => this.api.updateFactureFournisseur(id, draft).pipe(map((d) => AchatActions.updateFactureFournisseurSuccess({ factureFournisseur: d })), catchError((e) => of(AchatActions.updateFactureFournisseurFailure({ error: e?.message ?? 'Erreur' })))))));
  removeFactureFournisseur$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.removeFactureFournisseur), switchMap(({ id }) => this.api.removeFactureFournisseur(id).pipe(map(() => AchatActions.removeFactureFournisseurSuccess({ id })), catchError((e) => of(AchatActions.removeFactureFournisseurFailure({ error: e?.message ?? 'Erreur' })))))));

  loadAvoirsFournisseur$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.loadAvoirsFournisseur), switchMap(() => this.api.getAvoirsFournisseur().pipe(map((d) => AchatActions.loadAvoirsFournisseurSuccess({ avoirsFournisseur: d })), catchError((e) => of(AchatActions.loadAvoirsFournisseurFailure({ error: e?.message ?? 'Erreur' })))))));
  addAvoirFournisseur$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.addAvoirFournisseur), switchMap(({ draft }) => this.api.addAvoirFournisseur(draft).pipe(map((d) => AchatActions.addAvoirFournisseurSuccess({ avoirFournisseur: d })), catchError((e) => of(AchatActions.addAvoirFournisseurFailure({ error: e?.message ?? 'Erreur' })))))));
  updateAvoirFournisseur$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.updateAvoirFournisseur), switchMap(({ id, draft }) => this.api.updateAvoirFournisseur(id, draft).pipe(map((d) => AchatActions.updateAvoirFournisseurSuccess({ avoirFournisseur: d })), catchError((e) => of(AchatActions.updateAvoirFournisseurFailure({ error: e?.message ?? 'Erreur' })))))));
  removeAvoirFournisseur$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.removeAvoirFournisseur), switchMap(({ id }) => this.api.removeAvoirFournisseur(id).pipe(map(() => AchatActions.removeAvoirFournisseurSuccess({ id })), catchError((e) => of(AchatActions.removeAvoirFournisseurFailure({ error: e?.message ?? 'Erreur' })))))));

  loadRetoursFournisseur$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.loadRetoursFournisseur), switchMap(() => this.api.getRetoursFournisseur().pipe(map((d) => AchatActions.loadRetoursFournisseurSuccess({ retoursFournisseur: d })), catchError((e) => of(AchatActions.loadRetoursFournisseurFailure({ error: e?.message ?? 'Erreur' })))))));
  addRetourFournisseur$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.addRetourFournisseur), switchMap(({ draft }) => this.api.addRetourFournisseur(draft).pipe(map((d) => AchatActions.addRetourFournisseurSuccess({ retourFournisseur: d })), catchError((e) => of(AchatActions.addRetourFournisseurFailure({ error: e?.message ?? 'Erreur' })))))));
  updateRetourFournisseur$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.updateRetourFournisseur), switchMap(({ id, draft }) => this.api.updateRetourFournisseur(id, draft).pipe(map((d) => AchatActions.updateRetourFournisseurSuccess({ retourFournisseur: d })), catchError((e) => of(AchatActions.updateRetourFournisseurFailure({ error: e?.message ?? 'Erreur' })))))));
  removeRetourFournisseur$ = createEffect(() => this.actions$.pipe(ofType(AchatActions.removeRetourFournisseur), switchMap(({ id }) => this.api.removeRetourFournisseur(id).pipe(map(() => AchatActions.removeRetourFournisseurSuccess({ id })), catchError((e) => of(AchatActions.removeRetourFournisseurFailure({ error: e?.message ?? 'Erreur' })))))));
}
